title: Groq AI PowerSuite
emoji: 🚀
colorFrom: blue
colorTo: indigo
sdk: gradio
sdk_version: 4.19.2
python_version: "3.10"
app_file: app.py
pinned: false
hf_oauth: false
duplicated_from: John2121/groq-ai-powersuite
